name: CodeBuild

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  codebuild:
    runs-on: codebuild-lambda-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Echo
        run: |
          echo "running on codebuild lambda"
          echo "OS: $(uname -a)"
          aws sts get-caller-identity
