name: CodeBuild

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  codebuild:
    runs-on: codebuild-luketest-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Echo
        run: echo "codebuild"

        # echo "running on CodeBuild..."
        # echo "OS: $(uname -a)"
        # aws sts get-caller-identity
