name: CodeBuild

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  codebuild:
    runs-on: codebuild-gha-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Echo
        run: echo codebuild
